import {
  Button,
  Card,
  CardActions,
  CardContent,
  CardMedia,
  Typography,
} from "@mui/material";
import { Box, Grid } from "@mui/system";
import Link from "next/link";

export const metadata = {
  title: "Blogs",
  description: "Generated by create next app",
};

export default async function Page() {
  const response = await fetch("http://localhost:3000/api/blogs");
  const blogs = await response.json();
  return (
    <>
      <Grid container rowSpacing={1} columnSpacing={{ sx: 1, sm: 2, md: 3 }}>
        {blogs.map((blog) => (
          <Grid size={{ md: 6 }} key={blog.id}>
            <Card sx={{ display: "flex" }}>
              <CardMedia
                component="img"
                sx={{ width: "45%" }}
                image={`/img/${blog.img}`}
                alt=""
              ></CardMedia>
              <Box>
                <CardContent>
                  <Typography variant="h6" component="div">
                    {blog.name}
                  </Typography>
                  <Typography variant="subtitle1" component="div">
                    {blog.description.substring(0, 50) + "..."}
                  </Typography>
                </CardContent>
                <CardActions sx={{ display: "flex", justifyContent: "end" }}>
                  <Button
                    component={Link}
                    href={`/blogs/${blog.id}`}
                    size="small"
                    variant="outlined"
                  >
                    Detail
                  </Button>
                </CardActions>
              </Box>
            </Card>
          </Grid>
        ))}
      </Grid>
    </>
  );
}
